### ISSUE TITLE
Windows 10: Touch keyboard support

### ISSUE THREAD

**Issue by moigagoo** [braindefender/universal-layout#1]
Во-первых, спасибо за раскладку, чистый кайф 🙏

Проблема в том. что в этой раскладке нет тач-варианта, который включается в Tablet mode. Показывается какая-то гумозная огромная клавиатура без буквы w.

Может, можно как-то это легко пофиксить?

**Comment by braindefender** [comment]
Действительно, с буквой W (Ц) что-то не так именно в Tablet Mode. Скорее всего для этого режима раскладки создаются отдельно. Как именно – я не знаю. Мои выглядят так: 

![Screenshot_36](https://user-images.githubusercontent.com/4646110/57969006-e6c3e380-799b-11e9-9988-87a3a346eb36.png)
![Screenshot_37](https://user-images.githubusercontent.com/4646110/57969023-0a872980-799c-11e9-807e-93cedba486fb.png)

Буквы W здесь тоже нет. При этом, если поместить «ц» и «Ц» на 3-ий и 4-ый слои, то они вообще отображаются на букве Q. Странно это.

**Comment by moigagoo** [comment]
У меня так же выглядит. В целом, это ок. Странно ещё то, что swipe-клавиатура иногда работает, а иногла нет ¯\_(ツ)_/¯
