### ISSUE TITLE
Не появляется русская раскладка

### ISSUE THREAD

**Issue by moigagoo** [braindefender/universal-layout#11]
Установил через setup.exe. Английская раскладка появилась, а русская — нет. И в списке раскладок нет.

Перезагрузка не помогла.

Windows 11.

**Comment by moigagoo** [comment]
> Раскладка объединяет в себе русскую и английскую раскладки, которые переключаются по клавише Caps Lock

Понял, в чём дело... Крайне неудачное решение, на мой взгляд. У меня и кучи людей капс работает контролом.

Кроме того, без русского языкового пакета нельзя выбрать региональные настройки.

**Comment by moigagoo** [comment]
Может, можно как-то разделить снова на две раскладки?

А то пришлось пока колхозить:
- региональный формат вручную настраивать
- мапить Win+Space на Caps Lock, чтобы мышечная память не сошла с ума

**Comment by braindefender** [comment]
> Английская раскладка появилась, а русская — нет.

Да, файл раскладки один. Это менее удобно с точки зрения визуала (раскладка отображается только одна и непонятно какой язык сейчас установлен, если на клавиатуре нет индикатора CapsLock). Но, в свою очередь, это гораздо более удобно из-за багов Windows, т.к. она периодически добавляет стандартные раскладки и вместо списка из двух (Universal Layout, Standard Layout) вы получите три (а иногда и четыре) раскладки, которые будет уже затруднительно переключать через Win+Space.

> У меня и кучи людей капс работает контролом.

Думаю, таких людей хоть и много, но точно не большинство. Всем точно не угодишь. Например, есть люди, которые настроили себе немодальное переключение раскладок и привыкли к этому. А Universal Layout это одна раскладка, и что теперь?

> Может, можно как-то разделить снова на две раскладки?

Можно. Для этого нужно: 
- продублировать раскладку, 
- изменить параметры (например, назвать старую UniEn, новую UniRu) 
- перенести слой с русским языком на слой с английским
- убрать переключение на CapsLock для каждой клавиши слоя с русскими буквами.

> мапить Win+Space на Caps Lock, чтобы мышечная память не сошла с ума

Мышечная память, хоть и сильная, но переучить себя переключать язык на капс — дело пары-тройки дней.

**Comment by moigagoo** [comment]
> Мышечная память, хоть и сильная, но переучить себя переключать язык на капс — дело пары-тройки дней.

Если бы на нём не было Ctrl, то да, наверно :-) Но у меня много шорткатов с Ctrl, и палец уже сам ложится на капс.

Спасибо, принято! Попробую найти время и сделать разделённый вариант.

**Comment by Dimentium** [comment]
> > Мышечная память, хоть и сильная, но переучить себя переключать язык на капс — дело пары-тройки дней.
> 
> 
> 
> Если бы на нём не было Ctrl, то да, наверно :-) Но у меня много шорткатов с Ctrl, и палец уже сам ложится на капс.
> 
> 
> 
> Спасибо, принято! Попробуй найти время и сделать разделённый вариант.

Если помимо ctrl на caps_lock не висит escape для одиночного нажатия, то конфликта быть не должно. Через ahk можно сделать чтоб при удержании оно работало как ctrl, а при одиночном нажатии как смена режима. 

Сам сейчас не использую Windows и точный скрипт для ahk не подскажу.

**Comment by moigagoo** [comment]
Я уже сделал себе раздельные раскладки :-)

Правда, почему-то у них названия остались старые, хотя я менял в Properties.

Могу сделать PR, вдруг кому-то ещё так удобнее будет.

**Comment by moigagoo** [comment]
@braindefender подскажи, пожалуйста, как на Маке отредактировать твои раскладки? У меня теперь ещё и Мак, там тоже нужно разделить раскладку на две, как я уже сделал на Винде.

**Comment by braindefender** [comment]
Используй [Ukelele](https://software.sil.org/ukelele/). Эти раскладки были в нём созданы.

**Comment by sergevkim** [comment]
@moigagoo подскажи, PR будет сделан в ближайшем будущем или пока руки не доходят?

**Comment by moigagoo** [comment]
@sergevkim сделаю сегодня-завтра. Я не знал, что есть нужда :-)

**Comment by moigagoo** [comment]
https://github.com/braindefender/universal-layout/pull/12
