### ISSUE TITLE
Windows 10 18917: Won't appear in the layout list

### ISSUE THREAD

**Issue by moigagoo** [braindefender/universal-layout#2]
Раскладка не показывается в списке после копирования в System32 в последней Fast Ring-сборке.

**Comment by moigagoo** [comment]
Инсталляция скриптом решает проблему.

Полчаса без универсальной раскладки — это просто пытка! Я и не думал, что я _так_ привык к ней.

Огромное спасибо за неё 🙏

**Comment by braindefender** [comment]
> Инсталляция скриптом решает проблему.

Да, нужно поправить способ установки. Простого копирования недостаточно без файла реестра, который прописывает раскладку в систему.

> Я и не думал, что я так привык к ней.

К хорошему быстро привыкаешь.
