### ISSUE TITLE
на винде у меня модификатор работает только с правым альтом

### ISSUE THREAD

**Issue by metya** [braindefender/universal-layout#3]
А левый альт как модификатор не работает.
Так и должно быть, или у меня какой то баг с этим?)

И, и кстати, еще вопрос, а нет ли похожего решения для линукса?

**Comment by metya** [comment]
и еще в догонку вопрос, есть ли какая то возможно удалить раскладки теперь из системы?)
я про windows 10, конечно же.

**Comment by metya** [comment]
а есть какая то возможность удалить теперь раскладки из системы?
а то я не нашел никакого возможного способа, кроме как вручную. 

`uninstall.bat` не делает этого.

**Comment by braindefender** [comment]
> А левый альт как модификатор не работает.
> Так и должно быть, или у меня какой то баг с этим?)

Левый альт на Windows не работает как модификатор слоя. Я не нашёл как его заставить это делать.

> И, и кстати, еще вопрос, а нет ли похожего решения для линукса?

Нет, и не планируется. Я не использую Linux, если только кто-то законтрибьютит.

> а есть какая то возможность удалить теперь раскладки из системы?

Да, очистить запись в реестре и удалить файлы kbdunirus.dll и kbduniteng.dll из system32.

> uninstall.bat не делает этого

Да, он остался от исходного пакета с дизассемлером раскладок, надо пофиксить.
