### ISSUE TITLE
Версия для Линукса

### ISSUE THREAD

**Issue by moigagoo** [braindefender/universal-layout#5]
Здравствуйте!

Есть ли шанс сделать версию раскладки для Линуксов? В частности, хочется иметь такую раскладку для KDE.

**Comment by braindefender** [comment]
В данный момент я использую split клавиатуру с кастомной раскладкой, а не unversal-layout.
Поэтому Linux версию я делать не планирую, разве что кто-то из коммьюнити сделает.

**Comment by moigagoo** [comment]
FYI сделал версию для Линукса: https://github.com/moigagoo/universal-layout-linux
