### ISSUE TITLE
Не получается использовать маленький твердый знак 

### ISSUE THREAD

**Issue by haosmos** [braindefender/universal-layout#9]
Привет! 

Не получается использовать маленький твердый знак – если нажимать на правый или левый alt + M (англ.)/ь, то ничего не происходит. Но большой твердый знак вводится – Ъ. Остальные символы и спец. символы вводятся нормально. 

В чем может быть проблема? 

ОС: windows 22631.3527

**Comment by braindefender** [comment]
Я тоже сталкивался с подобной проблемой и на Windows 10, и на Windows 11. Есть ощущение, что сочетание клавиш AltGr+M перехватывается каким-либо приложением и оно перестаёт работать как символ. Причём, такое происходит именно с буквой Ъ, другие буквы/символы со слоя AltGr вводятся нормально.

Закономерности заметить не смог. Сейчас у меня на Windows 11 срабатывает всегда, как положено.

**Comment by faxcon08** [comment]
Добрый день. Благодарю за проделанную работу. У меня сочетание AltGr + M перехватывал Nvidea Experience (горячая клавиша выключение микрофона). Возможно, кому-нибудь поможет.

**Comment by faxcon08** [comment]
Windows 11 Домашняя, 23H2, сборка 22631.3593

**Comment by braindefender** [comment]
> Добрый день. Благодарю за проделанную работу. У меня сочетание AltGr + M перехватывал Nvidea Experience (горячая клавиша выключение микрофона). Возможно, кому-нибудь поможет.

Вот же блин, у меня тоже он был раньше установлен. Нужно затестить. Спасибо за информацию!
